graph TD
A[run_Oncorhynchus_mykiss] --> B[check_my_pet]
A --> C[estim_options]
A --> D[estim_pars]

D --> E[mydata_Oncorhynchus_mykiss]
D --> F[pars_init_Oncorhynchus_mykiss]
D --> G[predict_Oncorhynchus_mykiss]

E --> H[setweights]
E --> I[addpseudodata]

F --> J[addchem]
F --> K[parscomp_st]

G --> L[vars_pull]
G --> M[tempcorr]
G --> N[get_tj]
G --> O[initial_scaled_reserve]
G --> P[ode45]
G --> Q[scaled_power_j]
G --> R[reprod_rate_j]
G --> S[get_tm_j]
G --> T[maturity_j]
G --> U[predict_WL]

P --> V[dget_aul]
P --> W[dget_LUH]
P --> X[dget_LEHR]

U --> Y[ode45]
Y --> V
Y --> W